alter session set "_ORACLE_SCRIPT"=true;
CREATE USER JAVA IDENTIFIED BY JAVA DEFAULT TABLESPACE USERS;

GRANT ALL PRIVILEGES TO JAVA;

CREATE TABLE PERSONA
    (
        ID_PERSONA INTEGER NOT NULL,
        DOCUMENTO VARCHAR(20) NOT NULL,
        APELLIDO1 VARCHAR(30) NOT NULL,
        APELLIDO2 VARCHAR(30),
        NOMBRE1 VARCHAR(30) NOT NULL,
        NOMBRE2 VARCHAR(30),
        CONSTRAINT PK_PERSONA PRIMARY KEY (ID_PERSONA),
        CONSTRAINT UK_PERSONA_DOCUMENTO UNIQUE (DOCUMENTO)
    )
TABLESPACE "USERS";

SELECT * FROM PERSONA;
